### ISSUE TITLE
I'm getting error in frontend directory. 

### ISSUE THREAD

**Issue by mihirdoshi5199** [SiddharthSsb11/MERN-chat-app#1]
![image](https://user-images.githubusercontent.com/42415639/152942393-306c11d0-84e1-4835-a707-a15365cd8551.png)

**Comment by SiddharthSsb11** [comment]
Can you please elaborate more on this..

**Comment by mihirdoshi5199** [comment]
> Can you please elaborate more on this..

I have reinstalled npm, issue resolved. Thank you:)
