### ISSUE TITLE
Issue in Deployment

### ISSUE THREAD

**Issue by mihirdoshi5199** [SiddharthSsb11/MERN-chat-app#2]
I'm unable to deploy, can you please help me or ellaborate few more steps in deployment..

![image](https://user-images.githubusercontent.com/42415639/154012922-51633490-51c4-4dc8-9859-e1575519a309.png)

**Comment by SiddharthSsb11** [comment]
Have you pushed it to Heroku? 
If not, create a new application on Heroku. 
There is a Heroku post-build script in the root directory package.json file, so if you push your project directory to Heroku, then there is no need to build manually for deployment to Heroku. 
The post-build script does the building part for you if you push and deploy your project repo to heroku.

**Comment by mihirdoshi5199** [comment]
> Have you pushed it to Heroku? If not, create a new application on Heroku. There is a Heroku post-build script in the root directory package.json file, so if you push your project directory to Heroku, then there is no need to build manually for deployment to Heroku. The post-build script does the building part for you if you push and deploy your project repo to heroku.

Okay, I will try. Thank you for the response.
